name: message-moderation

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: app

    env_file:
      - ../.env

    command: "python app/application/main.py"
