name: message-moderation

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB__ADMIN_USERNAME:?}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB__ADMIN_PASSWORD:?}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB__ADMIN_USERNAME:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB__ADMIN_PASSWORD:?}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB__ADMIN_USERNAME:?}:${MONGODB__ADMIN_PASSWORD:?}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  dbdata:
