name: message-moderation

services:
  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    environment:
      - POSTGRES_DB=${POSTGRES__NAME:?}
      - POSTGRES_USER=${POSTGRES__USER:?}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "10432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  pgdata:
