name: message-moderation

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/var/lib/redis/data
    restart: always
    ports:
      - "6379:6379"
    command:
      - redis-server

volumes:
  redis-data:
